server:
  port: 8090
  shutdown: graceful

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: authentication
  datasource:
    url: jdbc:postgresql://ep-divine-snowflake-a2bwd3vl.eu-central-1.aws.neon.tech/db
    driver-class-name: org.postgresql.Driver
    username: kon.stantinnezhalsky
    password: MqcYfu7BipI2
    hikari.connectionTimeout: 100000
    hikari.idleTimeout: 600000
    hikari.maxLifetime: 1800000

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml


  mvc:
    static-path-pattern: /static/**

springdoc:
  api-docs:
    path: /swagger/desc
  swagger-ui:
    path: /swagger/ui

